default: &default
  adapter: mysql2
  encoding: utf8mb4
  username: root
  password:
  host: 'localhost'
  port: 3306

development:
  <<: *default
  database: 'chatbot_development'

test:
  <<: *default
  database: 'chatbot_test'

staging:
  <<: *default
  database: 'chatbot_staging'

production:
  <<: *default
  database: 'chatbot_production'
